---

- name: Install oVirt Hosted Engine base setup
  hosts: ovhs_master
  connection: local

  roles:
#    - displayfacts 
    - { role: ovhs.hostname, tags: ["networking"] }
    - { role: ovhs.etc_hosts, tags: ["networking"] }
    - { role: ovhs.network, tags: ["networking"] }
    - { role: ovhs.dnsmasq, tags: ["networking"] }
    - { role: ovhs.gluster, tags: ["storage"] }
#    - { role: ovirt.hosted_engine_setup, tags: ["ovirt"] }
