---

- name: setup oVirt host
  hosts: ovhs
  gather_facts: no
    
  roles:
# packages: gdeploy cockpit-ovirt-dashboard vdsm-gluster ovirt-engine-appliance
#    - { role: ovhs-base-config, tags: ["ovhs-base-config"] }
#    - ovhs-gluster-master
 #       tags: "ovhs-gluster-master"
#    - { role: ovhs-ovirt-install, tags: ["ovhs-ovirt-install"] }
    - hostname
#  vars_files:
#    - vars/network.yml
