- hosts: localhost
  become: true
  tasks:
  - name: Upgrade all packages
    yum: name=* state=latest
    tags: packages

  - name: Configure firewall
    firewalld: port=9090/tcp permanent=true state=enabled
    tags: services

  - name: Install packages
    yum: name={{ item }} state=latest
    with_items:
#     - kbd
     - vim
#     - parted
#     - bridge-utils
     - chrony
     - cockpit-dashboard
     - cockpit-storaged
     - cockpit-machines
    tags: packages
    notify:
     - restart cockpit

  - name: Enable services
    service: name={{ item }} state=started enabled=yes
    with_items:
     - cockpit.socket
     - chronyd
    tags: services
