---

ovhs_hostname:      "ovhs01"
ovhs_hostname_back: "{{ ovhs_hostname }}-back"
ovhs_hostname_dmz:  "{{ ovhs_hostname }}-dmz"
ovhs_if_mgmt:       "enp2s0"
ovhs_if_public:     "enp3s0"
ovhs_if_back:       "enp4s1"
ovhs_if_dmz:        "{{ ovhs_if_back }}.1"
ovhs_ipv4_mgmt:     "{{ ovhs_network_mgmt }}.0.101"
ovhs_ipv4_public:   "dhcp"
ovhs_ipv4_back:     "{{ ovhs_network_back }}.0.101"
ovhs_ipv4_dmz:      "{{ ovhs_network_dmz }}.0.101"
he_fqdn: "engine.ovhs.home"
he_bridge_if: "{{ ovhs_if_mgmt }}"
he_vm_mac_addr: "00:a5:3f:66:ba:12"
he_domain_type: "glusterfs"
he_host_name: "{{ ovhs_hostname }}.{{ ovhs_domain_name }}"
#he_storage_domain_name: "HostedEngine"
he_storage_domain_addr: "172.20.0.101"
he_storage_domain_path: "{{ ovhs_storage_hostname }}.{{ ovhs_domain_name }}:/engine"
he_vm_ip_addr: "172.20.0.100"
he_vm_ip_prefix: "24"
he_dns_addr: "172.20.0.101"
he_default_gateway: "172.20.0.101"
he_force_ip4: true
he_vcpus: "2"
