---

# ovhs_gluster related packages
ovhs_gluster_packages:
  - http://resources.ovirt.org/pub/yum-repo/ovirt-release-master.rpm
  - gdeploy
  - cockpit-ovirt-dashboard
  - vdsm-gluster
  - ovirt-engine-appliance

