---

- name: Configure firewall for DNS
  firewalld: service=dns permanent=true state=enabled
  tags: network

- name: Add localhost to /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver 127.0.0.1'
    line: "nameserver 127.0.0.1"
    insertbefore: '^nameserver.*'
    state: present
    create: yes

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: yes
    state: started

- name: Configure dnsmasq
  template:
    src: etc/dnsmasq.d/dnsmasq-ovhs.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq-ovhs.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - 'restart dnsmasq'
