---

- name: Add the mgmt network inventory to /etc/hosts.dnsmasq
  lineinfile:
    path: /etc/hosts.dnsmasq
    regexp: '.*{{ hostvars[item]["ovhs_hostname"] }}\..*'
    line: "{{ hostvars[item]['ovhs_ipv4_mgmt'] }} {{ hostvars[item]['ovhs_hostname'] }}.{{ ovhs_domain_name }} {{ hostvars[item]['ovhs_hostname'] }} # {{ item }}"
    state: present
    create: yes
  when: hostvars[item]['ovhs_ipv4_mgmt'] is defined
  with_items:
    - "{{ groups['all'] }}"
  notify:
    - 'restart dnsmasq'

- name: Add the backend network inventory to /etc/hosts.dnsmasq
  lineinfile:
    path: /etc/hosts.dnsmasq
    regexp: '.*{{ hostvars[item]["ovhs_hostname_back"] }}\..*'
    line: "{{ hostvars[item]['ovhs_ipv4_back'] }} {{ hostvars[item]['ovhs_hostname_back'] }}.{{ ovhs_domain_name }} {{ hostvars[item]['ovhs_hostname_back'] }} # {{ item }}"
    state: present
    create: yes
  when: hostvars[item]['ovhs_ipv4_back'] is defined
  with_items:
    - "{{ groups['all'] }}"
  notify:
    - 'restart dnsmasq'

- name: Add the dmz network inventory to /etc/hosts.dnsmasq
  lineinfile:
    path: /etc/hosts.dnsmasq
    regexp: '.*{{ hostvars[item]["ovhs_hostname_dmz"] }}\..*'
    line: "{{ hostvars[item]['ovhs_ipv4_dmz'] }} {{ hostvars[item]['ovhs_hostname_dmz'] }}.{{ ovhs_domain_name }} {{ hostvars[item]['ovhs_hostname_dmz'] }} # {{ item }}"
    state: present
    create: yes
  when: hostvars[item]['ovhs_ipv4_dmz'] is defined
  with_items:
    - "{{ groups['all'] }}"
  notify:
    - 'restart dnsmasq'
