---

- name: Add the mgmt network inventory to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ovhs_ipv4_mgmt'] }} {{ hostvars[item]['ovhs_hostname'] }}.{{ hostvars[item]['ovhs_domain_name'] }} {{ hostvars[item]['ovhs_hostname'] }} {{item}}"
    state: present
  when: hostvars[item]['ovhs_ipv4_mgmt'] is defined
  with_items:
    - "{{ groups['all'] }}"

- name: Add the backend network inventory to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ hostvars[item]["ovhs_hostname_back"] }}$'
    line: "{{ hostvars[item]['ovhs_ipv4_back'] }} {{ hostvars[item]['ovhs_hostname_back'] }}.{{ hostvars[item]['ovhs_domain_name'] }} {{ hostvars[item]['ovhs_hostname_back'] }}"
    state: present
  when: hostvars[item]['ovhs_ipv4_back'] is defined
  with_items:
    - "{{ groups['all'] }}"

- name: Add the dmz network inventory to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ hostvars[item]["ovhs_hostname_dmz"] }}$'
    line: "{{ hostvars[item]['ovhs_ipv4_dmz'] }} {{ hostvars[item]['ovhs_hostname_dmz'] }}.{{ hostvars[item]['ovhs_domain_name'] }} {{ hostvars[item]['ovhs_hostname_dmz'] }}"
    state: present
  when: hostvars[item]['ovhs_ipv4_dmz'] is defined
  with_items:
    - "{{ groups['all'] }}"
