---

- name: install packages for template
  package:
    name: '{{ template_packages }}'
    state: present

- name: remove template
  package:
    name: '{{ template_packages_removed }}'
    state: absent
